[project]
name = "avship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.0",
    "joblib>=1.5.3",
    "numpy>=2.0.2",
    "pydantic>=2.12.5",
    "uvicorn>=0.39.0",
]
